"""modified Groups table

Revision ID: e630fd6adf22
Revises: b9609e1adf86
Create Date: 2026-04-16 22:07:25.043310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e630fd6adf22'
down_revision = 'b9609e1adf86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key("fk_group_created_by_user", 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_group_created_by_user', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
